server:
  port: 8080


spring:
  application:
    name: test
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?charset=utf8mb4&serverTimezone=UTC
    username: root
    password: root

    hikari:
      maximum-pool-size: 20
      minimum-idle: 5

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

  redis:
    database: 6
    host: 127.0.0.1
    port: 6379
    password: 123456
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        min-idle: 8
        max-idle: 0
        timeout: 3000
#  data:
#    mongodb:
#      uri: mongodb://192.16.1.24:27017/test

#  cache:
#    cache-names: studentById
#    type: caffeine
#    caffeine:
#      #refreshAfterWrite=10s need LoadingCache
#      #spec: maximumSize=500,expireAfterWrite=10s,refreshAfterWrite=10s
#      spec: maximumSize=500,expireAfterWrite=10s

xxl:
  job:
    admin:
      address: http://127.0.0.1:18080/xxl-job-admin
    executor:
      appname: demo-test
      # 执行器IP [选填]：默认为空表示自动获取IP，多网卡时可手动设置指定IP，
      # 该IP不会绑定Host仅作为通讯实用；地址信息用于 "执行器注册" 和 "调度中心请求并触发任务"
      ip:
      # 执行器端口号 [选填]：小于等于0则自动获取；默认端口为9999，单机部署多个执行器时，
      # 注意要配置不同执行器端口
      port: 9998
      logpath: /xxl-job-log
      logretentiondays: 10
    accessToken:
